### ISSUE TITLE
 ObjectsApi uploadChunk problem

### ISSUE THREAD

**Issue by wangsidong** [Autodesk-Forge/forge-api-java-client#10]
i am using ObjectsApi uploadChunk but it do not work，
how can i upload the big file by chunk to autodesk
is there any example for this api，thanks verymuch

ApiResponse<ObjectDetails> response = objectsApi.uploadObject(BUCKET_KEY, FILE_NAME, (int)fileToUpload.length(), fileToUpload, null, null, oauth2TwoLegged, twoLeggedCredentials);    
//ApiResponse<ObjectDetails> response = objectsApi.uploadChunk(BUCKET_KEY, FILE_NAME, (int)fileToUpload.length(), "Range:bytes=0-1000",DdDateTimeUtils.currentTimeMillis()+"", fileToUpload, null, null, oauth2TwoLegged, twoLeggedCredentials);

**Comment by leefsmp** [comment]
The minimum chunk size is 3M (3 * 1024 * 1024), you are trying to upload 1000 bytes. Take a look at this [node.js sample](https://gist.github.com/leefsmp/f66c86930e038d2d808808cb95c027c5) that makes use of the uploadChunch method. Hope that helps.

**Comment by xiaodongliang** [comment]
it looks @leefsmp  has helped the quetion. @wangsidong i will close this issue, while please feel free to log new or re-open if the problem still exists.
