### ISSUE TITLE
Maven dependency 1.0.0 not found

### ISSUE THREAD

**Issue by jaimerosales** [Autodesk-Forge/forge-api-java-client#12]
Missing Maven Dependency for 1.0.0 version.

**Comment by asultanpur** [comment]
The only version available seems to be `1.0.1`, but the documentation mentions `1.0.0`.

**Comment by jaimerosales** [comment]
@asultanpur We had to push an upgrade, so the one to use will be 1.0.1, I will take care of the Documentation part :) thanks for letting us know.
