### ISSUE TITLE
IFC is missing in JobPayLoadItem.TypeEnum

### ISSUE THREAD

**Issue by ktoure360** [Autodesk-Forge/forge-api-java-client#18]
Hello
I want to perform a translate of .rvt file to .ifc file but TypeEnum does not have IFC and RVT. The actual api supports them.
Can you please add them?

Thanks

**Comment by augustogoncalves** [comment]
@dukedhx  you assigned that to you, did you submit a PR?

**Comment by dukedhx** [comment]
Already addressed in [here](https://github.com/Autodesk-Forge/forge-api-java-client/commit/89e390243ef64dba171affa0b38b4a8b0afed9db)
```
jobPayLoadItem.setType(JobPayloadItem.TypeEnum.IFC);
jobPayLoadItem.setType(JobPayloadItem.TypeEnum.RVT);
```
