### ISSUE TITLE
return null getModelviewMetadata

### ISSUE THREAD

**Issue by zhb123168** [Autodesk-Forge/forge-api-java-client#2]
return null the **getModelviewMetadata** method,

the same argument Manual Call is right.

return new ApiResponse<T>(statusCode, responseHeaders, response.getEntity(returnType));  -- null

**Comment by einat-bar** [comment]
@zhb123168  - Thanks, working on a fix for this issue.

**Comment by einat-bar** [comment]
@zhb123168  - Issue is fixed
