### ISSUE TITLE
getDerivativeManifest does not return a File

### ISSUE THREAD

**Issue by TiagoRaposoBR** [Autodesk-Forge/forge-api-java-client#27]
getDerivativeManifest "Downloads a selected derivative", according to the description of the method. However, it doesn't return a File, instead the return is an ApiResponse of type Void. (DerivativesApi.java:135)

getThumbnail does return a File. Shouldn't getDerivativeManifest return one too, or maybe a new method (downloadDerivative) that returns an ApiResponse<File>?

**Comment by dukedhx** [comment]
Thanks for letting us know. Will fix this soon
