### ISSUE TITLE
derivativesApi.getManifest doesn't give camera information in SVF derivative

### ISSUE THREAD

**Issue by vaibhav-bhandari** [Autodesk-Forge/forge-api-java-client#31]
I am using derivativesApi.getManifest API to get the camera information of revit.
When using the core forge API I do get the camera information under SVF derivative's children having 3D role.

**Comment by dukedhx** [comment]
will address this in the next commit

**Comment by vaibhav-bhandari** [comment]
@dukedhx  Could you please look into the created pull request and let me know for any concern 
https://github.com/Autodesk-Forge/forge-api-java-client/pull/32
