### ISSUE TITLE
Missing Pagination on all endpoints

### ISSUE THREAD

**Issue by julillosamaral** [Autodesk-Forge/forge-api-java-client#35]
Hi,

I don't see a way to send the pagination information to the API calls. Is that correct? Is there a plan to add it?

I can try to add it but need to know how much it would take to send it to master and publish it. If it takes a couple of days I can do it next week if not I have to schedule it for the future.

Regards,
Julio

**Comment by dukedhx** [comment]
not exactly on our roadmap so PR welcomed

**Comment by julillosamaral** [comment]
@dukedhx  How long does it take to send a PR into master?

Regards,
Julio
