### ISSUE TITLE
Missing Endpoint: https://developer.api.autodesk.com/modelderivative/v2/regions/eu/designdata/:urn/metadata

### ISSUE THREAD

**Issue by juriritter** [Autodesk-Forge/forge-api-java-client#36]
Hi I need to use the endpoint ":urn/metadata" for EU described here: 

https://forge.autodesk.com/en/docs/model-derivative/v2/reference/http/urn-metadata-GET/

Instead of this endpoint: https://developer.api.autodesk.com/modelderivative/v2/designdata/:urn/metadata
I need this one: 
https://developer.api.autodesk.com/modelderivative/v2/regions/eu/designdata/:urn/metadata

The method I am calling is: 
response = derivateApi.getMetadata(urn, "*", oauth2TwoLegged, twoLeggedCredentials);

I need some how a flag.

Thank you in advance!
Juri

**Comment by dukedhx** [comment]
nominated for next commit

**Comment by xiaodongliang** [comment]
@juriritter  the **region** is now added with the commit https://github.com/Autodesk-Forge/forge-api-java-client/commit/34f49cc52b0d7253adb873f7fa1a34b687654690 .  thanks for your patience!
