### ISSUE TITLE
Improve design of the library

### ISSUE THREAD

**Issue by julillosamaral** [Autodesk-Forge/forge-api-java-client#37]
This is a really big task.

I found the design of the library really bad and this is because many times I've found bugs or missing parts of the API specification reflected in the library.
First of all there's no interfaces in the library, this causes the developer having to extend a complete function and all the functions and objects inside of it. I'll add a concrete example so it's more clear.

On `DerivativesApi` we have the function `translate` to convert from one format to other. In my case I want to convert from RVT to DWG, this is supported by the API but not by the library.

I find myself on a position to have to re implement `translate`, JobPayload, JobPayloadOutput and JobPayloadItem. In JobPayloadItem I finally have the option to re create TypeEnum and add the  missing (DWG). 

If the code had interfaces I would only have to implement one class (JobPayloadItem), everything else would works in the same way.

It's been really difficult to work with this. Is the library deprecated? Is something you're working on? Something it's not deprecated but should?

Regards,
Julio

**Comment by dukedhx** [comment]
agree the overall design pattern of this SDK can use some improvement but currently we dont really have plans to restructure/refractor this SDK so if you have the bandwidth feel free to PR or even start a new project - any input would be appreciated

**Comment by julillosamaral** [comment]
Do you guys have the swagger doc for the API?
I'm thinking that the correct way to do this is generating the clients from the documentation and not having a client library that needs to be updated.

if you send me that doc I can try it on one of my projects.

This has a big advantage for you, instead of maintaining each client for each language you just generate the doc and everyone can use it as they want.

**Comment by dukedhx** [comment]
We would certainly gone with that approach if possible - unfortunately the OpenAPI definitions are not available for public access just yet for security reasons such as that there are internal endpoints that have yet to be released included in the definitions. Will let you know when they become available.
