### ISSUE TITLE
Incorrect Value for ExpiresAt when calling the authenticate method in OAuth2TwoLegged.

### ISSUE THREAD

**Issue by dallanmc** [Autodesk-Forge/forge-api-java-client#4]
If I call the `OAuth2TwoLegged.authenticate` method I get a value for `expiresAt` which corresponds to a date which is about 2 years and 10 months into the future.

Looks like there is a bug in the code for the `OAuth2TwoLegged` (and `ThreeLegged`) class.

`DateTime later = DateTime.now().plusSeconds( (int)expires_in * 1000 ); `

It looks like the expires_in value should not be multiplied by 1000. The expires_in value is already in seconds (and not milliseconds).

When changed, this code will produce a value for `expiresAt` which is 24 hours in the future instead of nearly 3 years.

**Comment by einat-bar** [comment]
Thanks @dallanmc. We are working to fix this issue.
