### ISSUE TITLE
FoldersApi getFolder doesnt return folder attributes

### ISSUE THREAD

**Issue by atelyshev** [Autodesk-Forge/forge-api-java-client#44]
Here simple code that doesnt return waht it needs , at least REST gives it.

       var ret = _foldersApi.getFolder(
                <projectId>,
                <folderId>,
                _oauth2TwoLegged,
                _twoLeggedCredentials);

result = {Folder@7649} "class Folder {\n    jsonapi: class JsonApiVersionJsonapi {\n
        version: 1.0\n    }\n    
data: class JsonApiResource {\n        
id: urn:adsk.wipprod:fs.folder:co.nuR9pf6MRjaqgfeRv6wbZg\n        
type: folders\n        attributes: class JsonApiAttributes {\n        
}\n
        meta: null\n
        relationships: class JsonApiRelationships {\n        
}\n        
links: class JsonApiLinks {\n        
}\n    
}\n    included: []\n    
links: class JsonApiLinks {\n
    }\n    
id: null\n    
type: null\n    
attributes: null\n    
meta: null\n    
relationships: null\n}"
 jsonapi = {JsonApiVersionJsonapi@7652} "class JsonApiVersionJsonapi {\n  
  version: 1.0\n
}"
 data = {JsonApiResource@7653} "class JsonApiResource {\n   
 id: urn:adsk.wipprod:fs.folder:co.\n
    type: folders\n
    attributes: class JsonApiAttributes {\n    
}\n    
meta: null\n    
relationships: class JsonApiRelationships {\n    
}\n    
links: class JsonApiLinks {\n
    }
\n}"
  id = "urn:adsk.wipprod:fs.folder:co."
  type = "folders"
  attributes = {JsonApiAttributes@8483} "class JsonApiAttributes {\n}"
   **Class has no fields**
  meta = null

**Comment by xiaodongliang** [comment]
@atelyshev  commit at https://github.com/Autodesk-Forge/forge-api-java-client/commit/d6440970e541bba700ca6d53f4d1c8019337b03d  with updated Folder class and JsonApiAttributes. Please check if it works now. The two_legged_bim360_dm is a test script.
