### ISSUE TITLE
https://developer.autodesk.com/en/docs/oauth/v2/reference/http/users-@me-GET/

### ISSUE THREAD

**Issue by cyrillef** [Autodesk-Forge/forge-api-java-client#5]
This endpoint is missing from the SDK

**Comment by harmanpa** [comment]
+1

**Comment by xiaodongliang** [comment]
added in commit https://github.com/Autodesk-Forge/forge-api-java-client/commit/3fda30b8ca1430a75520b97cd6e8629c46faf4dc
