### ISSUE TITLE
Missing Endpoint GET hubs/:hub_id/projects/:project_id/topFolders

### ISSUE THREAD

**Issue by jaimerosales** [Autodesk-Forge/forge-api-java-client#9]
The access to Top Folders is missing from the SDK
GET hubs/:hub_id/projects/:project_id/topFolders

**Comment by julillosamaral** [comment]
@jaimerosales Maybe it's a bit to late but I created a PR to fix this: https://github.com/Autodesk-Forge/forge-api-java-client/pull/34

Can you check it or help me to get it into master?

Regards,
Julio Sarachaga

**Comment by xiaodongliang** [comment]
This PR has been merged. Thank you @julillosamaral ! closing this issue now
